DESKTOP-version pull
Ramaunspoken/Portfolio-First-Mobile pull request #5
Opened 2022-11-09 13:42 UTC by Ramaunspoken

Created the css and html for the Desktop version of the portfolio.

2022-11-09 16:19 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle: 

Hi @Ramaunspoken, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-   Correct GitHub Flow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-09 16:19 UTC, Qoosim commented on index.html
> +        </div>
- [ ] Greate job for  making it this far, I must commend your effort for that. :handshake: . However, on the desktop version of your project, you're supposed to display the menu items at the top right corner of your page as we have it on the Figma template you're mimicking. Those navigation items are not present on your page. Kindly look at the both designs, find out the differences and work your project in line with the Figma design. Thank you.

### Your Design

![your-menu-items](https://user-images.githubusercontent.com/26597432/200878189-4922fef8-6bab-4498-a4f2-54ccc56d6b34.png)

### Figma Design

![figma-menu-items](https://user-images.githubusercontent.com/26597432/200878230-5d17abdc-f4a2-461d-9b5e-d43fe71ce2a5.png)

2022-11-09 16:19 UTC, Qoosim commented on index.html
> +        </div>
- [ ] Looking at the design on the Figma template. The card is divided into two equal parts. One for the image and the other one for the image info. In your own case, the info part takes a larger part of the card which is not in line with what we have on the guiding template. Kindly make your project to produce a close replica of what we have on the guiding template. This applies to all other work-cards in your project. Take a look at the both designs and work your design along side with the guiding template.

### Your Design

![your-project-card](https://user-images.githubusercontent.com/26597432/200880047-ae887876-af15-45a7-a0aa-1cdae9843937.png)

### Figma Design

![figma-project-card](https://user-images.githubusercontent.com/26597432/200880355-56bcad49-19b1-4f77-b827-6cf9a496f664.png)

2022-11-09 16:19 UTC, Qoosim commented on index.html
> +      </section>
- [ ] You also need to work on this section of your project in order to produce the exact design of what we have on the Figma template. Consider giving your about section margin or padding to the both sides and give more width to `languages` side than `about me` side. Take a look at the both designs and fix your project to produce what is on the Figma template.

#### Your Design

![your-about-section](https://user-images.githubusercontent.com/26597432/200881829-0fee167e-1979-428a-ad70-6ada951c77ff.png)

### figma Design
![figma-about-section](https://user-images.githubusercontent.com/26597432/200881871-303e7df2-2e4f-41cb-b04a-f0e0c9f9e55a.png)

2022-11-09 16:19 UTC, Qoosim commented on index.html
> +        </form>
- [ ] Your contact me section also needs some adjustment. The text at the top of your form covers more space compare to what is on the Figma design. kindly take a look at both designs and adjust your design to produce what we have on the guiding template.
- [ ] Kindly take note of the position of the `Get in touch` button on the desktop. It is ought to be aligned to the center of the form. Kindly look into that too and fix it.

### Your Design
![your-contact-section](https://user-images.githubusercontent.com/26597432/200882630-6166ba98-6309-4a86-a527-8e853311b33a.png)

### Figma Design

![figma-contact-section](https://user-images.githubusercontent.com/26597432/200882678-86cff8f6-0442-4e73-87e5-1b562d9b7a2c.png)

2022-11-10 15:43 UTC, Nemwel-Boniface approved these changes
## Hello @Ramaunspoken      :wave: ,
I am Nemwel your reviewer for this PR :man_beard:  

Thank you for making the requested changes good job! :partying_face: 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! :partying_face: 🎉 

![](https://media.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif)

## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️ 
Met all the milestone requirements ✔️ 

## [Optional] suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-11 06:45 UTC, merged